### PR TITLE
does not error out when run from node without a dom

### PR DESCRIPTION
**Pull request by antialias**

### CODE REVIEW

**Comment by antialias** [comment]
@TooTallNate

**Comment by antialias** [comment]
specs are failing because saucelabs credentials are incorrect

screen shot 2016-06-23 at 1 31 06 pm

**Comment by TooTallNate** [comment]
The changes look fine to me, but can I ask why you're trying to use this module in Node.js in the first place? It's designed for usage in the web browser.

**Comment by antialias** [comment]
I'm building a somewhat large library bundle in a package intended for universal rendering. Lots of modules are getting built into the bundle but only some of the code is intended for use on the server. For example:

``` js
// browserOnlyComponent.js
var CustomEvent = require('custom-event')
...

// universalComponent.js
...

// entry.js - webpack entry for building bundle.js
module.exports = {
  browserOnlyComponent: require('./browserOnlyComponent'),
  universalComponent: require('./universalComponent');
}
```

Now when I do:

``` sh
webpack --output-library-target commonjs2 ./entry bundle.js
node -e "require('./bundle.js')" bundle
```

the code in `custom-event` gets run because it is required by `browserOnlyComponent`, but I won't be using it.

**Comment by TooTallNate** [comment]
I would recommend that you take a look at utilizing the `"browser"` field in your app's package.json file. That way, webpack will use that as the entry point, and Node.js will use the `"main"` field as its entry point. You can fork code-paths at that point, which would avoid requiring browser-only modules like this one on the Node.js side.

**Comment by antialias** [comment]
Ouch. Can you give an example of how that would be set up? I'm trying to get custom-event to not error out when run by node, so if I could tell node to use a null package instead of custom-event, what you're suggesting could work, but I don't think node observes package.browser or anything like it natively.

It's my opinion that the simplest solution would be to have this package not throw an error when run inside of a non-browser environment.

For what it's worth, I'd like to point out that most of the changes that appear in this PR go away when whitespace is ignored: https://github.com/webmodules/custom-event/pull/1/files?w=1

**Pull request closed without merging**
